package com.smartcampus.enums;

public enum NotificationType {
  BOOKING_SUBMITTED,
  BOOKING_APPROVED,
  BOOKING_REJECTED,
  BOOKING_CANCELLED,
  TICKET_SUBMITTED,
  TICKET_STATUS_CHANGED,
  TICKET_ASSIGNED,
  TICKET_NEW_COMMENT
}

